### ISSUE TITLE
Exception: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by andyp05** [plmilord/Hass.io-custom-component-spaclient#10]
Keep seeing this in the logs. Otherwise seems to be working ok.

```
2021-11-11 14:11:30 ERROR (MainThread) [custom_components.spaclient.const] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/spaclient/config_flow.py", line 52, in async_step_user
await validate_input(self.hass, user_input)
File "/config/custom_components/spaclient/config_flow.py", line 96, in validate_input
if entry.data[CONF_HOST] == data[CONF_HOST]:
TypeError: string indices must be integers
```

In configuration.yaml

```
spaclient:
    name: tub
    host: 192.168.1.159
```

The IP is verified correct.
Using latest HA 2021.11.1 on PI4. Everything is updated.

Thanks

**Comment by plmilord** [comment]
Hello @andyp05,

As stated in my README.md, please install the Spa Client integration through the Home Assistant integrations menu:


===
1-Copy these project files into your Home Assistant `/config/custom_components` directory.

2-Install Spa Client integration through the Home Assistant integrations menu (you may need to press F5 in your browser to refresh Home Assistant cache files so that it appears in the menu of available integrations).

3-Enjoy!
===


I've also in my task list to `Bring back the ability to configure this custom component via the entries in configuration.yaml`

'Sorry for this limitation ... but for the rest, you will be amazed! ;-)
