### ISSUE TITLE
Entity missing? 

### ISSUE THREAD

**Issue by enkrypt3d** [plmilord/Hass.io-custom-component-spaclient#20]
I used to have an orange graph that showed the entity for when the heater is running.... 

![image](https://user-images.githubusercontent.com/93238214/170605143-4f9fa463-3501-4fd3-9e48-8414b46b3101.png)

Now it's completely gone. On the latest version of HA.

**Comment by plmilord** [comment]
Everything's fine on my side... Here's my setup:

Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

Sounds like a web browser cache issue!?

Have you tried:
- different web browser?
- clear web browser cache?
- Uninstall/reinstall the component?

Let me know your walkthrough...

**Comment by plmilord** [comment]
No need to show the heater heating as there's no heating... your target temperature was 50F and your current temperature was close to 80F, dropping! It also looks like you have disabled the temperature range and heating mode (because the current temperature reading goes to nothing at times... normal behavior of your controller).

**Comment by enkrypt3d** [comment]
ok once it cools down I'll run it again and see if the entity shows up... odd that it just disappears though when it's not in use?

**Comment by plmilord** [comment]
...and, everything's come back to normal?

**Comment by enkrypt3d** [comment]
we can close this for now. I'll re-open it later on this year when it's hot tub season if there is an issue. Thanks for your support!
